#ifndef _BDROID_BUILDCFG_H
#define _BDROID_BUILDCFG_H

#define BTM_DEF_LOCAL_NAME   "Lenovo K3 Note"

// Networking, Capturing, Object Transfer
// MAJOR CLASS: COMPUTER
// MINOR CLASS: PALM SIZE PC/PDA
#define BTA_DM_COD {0x1A, 0x01, 0x14}

//#define BTIF_HF_SERVICES (BTA_HSP_SERVICE_MASK)
//#define BTIF_HF_SERVICE_NAMES  { BTIF_HSAG_SERVICE_NAME, NULL }
#define KERNEL_MISSING_CLOCK_BOOTTIME_ALARM TRUE
//#define PAN_NAP_DISABLED TRUE

#endif
